name: Pull Request Discord Notification

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '🔔 新的 Pull Request！\n**標題**: ${{ github.event.pull_request.title }}\n**作者**: ${{ github.event.pull_request.user.login }}\n**分支**: ${{ github.event.pull_request.head.ref }} ➡️ ${{ github.event.pull_request.base.ref }}\n**連結**: ${{ github.event.pull_request.html_url }}'
